# Generated by Django 5.0.4 on 2025-06-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_options_alter_userprofile_managers_and_more'),
        ('accounts', 'make_location_migration'),
    ]

    operations = [
    ]
