# Generated by Django 5.0.4 on 2025-06-16 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20250616_0946'),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location',
            field=models.CharField(choices=[('westlands', 'Westlands'), ('dagoretti_north', 'Dagoretti North'), ('langata', 'Langata'), ('kibra', 'Kibra'), ('roysambu', 'Roysambu'), ('kasarani', 'Kasarani'), ('ruaraka', 'Ruaraka'), ('embakasi_south', 'Embakasi South'), ('embakasi_north', 'Embakasi North'), ('embakasi_central', 'Embakasi Central'), ('embakasi_east', 'Embakasi East'), ('embakasi_west', 'Embakasi West'), ('makadara', 'Makadara'), ('kamukunji', 'Kamukunji'), ('starehe', 'Starehe'), ('mathare', 'Mathare'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.CreateModel(
            name='ComplaintActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='complaint_activities/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='complaints.complaint')),
                ('officer', models.ForeignKey(limit_choices_to={'role': 'officer'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Complaint Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
