# Generated by Django 5.0.4 on 2025-06-17 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20250616_0946'),
        ('complaints', '0002_complaint_assigned_officer_alter_complaint_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_complaints', to='accounts.userprofile'),
        ),
    ]
