# Generated by Django 5.0.4 on 2025-06-18 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_user'),
        ('complaints', '0003_complaint_date_resolved'),
    ]

    operations = [
    ]
