# Generated by Django 5.0.4 on 2025-06-18 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_merge_20250618_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='date_resolved',
        ),
    ]
